config/routes.rb
WaiterUp::Application.routes.draw do
  root to: 'static_pages#root'

  resource :user, except: [:destroy]
  resource :provider, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :places, only: [:index, :show, :create] do
      get 'search', on: :collection
    end
    resources :menu_items, only: [:show, :destroy, :create, :update]
    resource :rating, only: [:create]
    resources :comments, only: [:create, :destroy]
    resources :categories
    resources :menus, only: [:create, :update, :destroy]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  provider        :boolean          default("false")
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  attr_reader :password

  has_many :places, inverse_of: :owner,
    class_name:  :Place,
    foreign_key: :owner_id,
    primary_key: :id

  has_many :ratings,
    class_name:  :Rating,
    foreign_key: :rater_id,
    primary_key: :id

  has_many :comments

  accepts_nested_attributes_for :places #, reject_if :place_already_exists #=> to be implemented

  validates :email, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6 }, allow_nil: true

  before_validation do
    self.session_token ||= SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    user.nil? || !user.is_password?(password) ? nil : user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password? password
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!
  rescue
    retry
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :verify_logged_in, only: [:show, :edit, :update]

  def new
    @user = User.new

    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash.now[:notice] = "Success!"
      log_in!(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages

      render :new
    end
  end

  def show
    @user = current_user

    render :show
  end

  def edit
    @user = current_user

    render :edit
  end

  def update
    @user = current_user

    if @user.update(user_params)
      flash.now[:notice] = "Success!"

      redirect_to user_url
    else
      flash.now[:errors] = @user.errors.full_messages

      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<% method = user.persisted? ? "PATCH" : "POST" %>
<% placeholder = user.persisted? ? user.email : "e.g. name@example.com" %>
<% btn_msg = user.persisted? ? "Update #{user.email}" : "Create Account" %>


<%= form_for(user, url: user_url) do |f| %>
  <input  type="hidden" name="_method" value="<%= method %>">

  <div class="form-group">
    <input type="text"
    name="user[email]"
    class="form-control"
    data-toggle="floatLabel" data-value="no-js"
    placeholder="Email">
    <label for="floatingLabels" style="color: #8ac">Email</label>
  </div>

  <div class="form-group">
    <input type="password"
    name="user[password]"
    class="form-control"
    data-toggle="floatLabel" data-value="no-js"
    placeholder="Password">
    <label for="floatingLabels" style="color: #8ac">Password</label>
  </div>

  <br>
  <%= f.submit btn_msg, class: "btn btn-primary", style: "width: 100%" %>
<% end %>

app/views/users/edit.html.erb
<div class="col-md-6 col-md-offset-3 login">
  <h3>Edit Account</h3>
  <br>
  <%= render 'form', user: @user %>
</div>

app/views/users/new.html.erb
<div class="col-md-3 col-md-offset-4 login">
  <h3>Create Account</h3>
  <a href="<%= new_provider_url %>">(as a provider)</a>
  <br>
  <br>
  <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="col-md-6 col-md-offset-3 login">  
<h3>Hello, <%= @user.email %></h3>

<%= button_to "Edit", edit_user_url, method: :get, class: "btn btn-primary" %>
</div>