config/routes.rb
WaiterUp::Application.routes.draw do
  root to: 'static_pages#root'

  resource :user, except: [:destroy]
  resource :provider, except: [:destroy]
  resource :session, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    resources :places, only: [:index, :show, :create] do
      get 'search', on: :collection
    end
    resources :menu_items, only: [:show, :destroy, :create, :update]
    resource :rating, only: [:create]
    resources :comments, only: [:create, :destroy]
    resources :categories
    resources :menus, only: [:create, :update, :destroy]
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer edit-menu">
  <small>
    WaiterUp
  </small>
  <nav>
    <ul>
      <li><%= link_to "see on github",
      "https://github.com/vveleva/WaiterUp" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse navbar-static-top">
  <div class="container">
    <!-- <%#= link_to "<div></div>".html_safe, "/#", id: "logo" %> -->

    <!-- <div id="logo">
    </div> -->
    <nav>
      <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          <!-- <li><%= link_to "Account", user_url %></li> -->
          <li><%= link_to "Logout", session_url, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign Up", new_user_url %></li>
          <li><%= link_to "Login", new_session_url %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WaiterUp</title>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <script type="text/javascript"  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7vYTae_GpOuNdjgPs1JkKzMFVBIHs7EE">
  </script>

  <script charset="utf-8">
  $(document).ready(function () {
    $('[data-toggle="floatLabel"]').attr('data-value', $(this).val()).on('keyup change', function () {
      $(this).attr('data-value', $(this).val());
    });
  });
  </script>
</head>

<body class="login-body">
  <%= render 'layouts/header' %>
  <div class="container">
    <div class="row">
      <div>
        <% if flash[:notice] %>
          <p><%= flash[:notice] %></p>
        <% end %>

        <% if flash[:errors] %>
          <div class='errors-box'>
            <div class="alert alert-danger" role="alert">
              <% flash[:errors].each do |err| %>
              <div class='field-with-error'>
                <span class="glyphicon glyphicon-exclamation-sign"
                      aria-hidden="true"></span>
                <span class="sr-only">Error:</span>
                <%= err %>
              </div>
              <% end %>
            </div>
          </div>
        <% end %>

        <%= yield %>

      </div>
    </div>
    <!-- <%#= render 'layouts/footer' %> -->
  </div>
</body>
</html>